### ISSUE TITLE
[feature] - Sex identifier.

### ISSUE THREAD

**Issue by Johannestegner** [personnummer/meta#11]
If reading the wiki article about personal identiy numbers, the third digit in the last four numbers is used to identify sex/gender (male odd, female even). We could easily introduce a function to fetch this from a number if wanted, but I'm not really sure it's a needed functionallity... What do you thing @frozzare ?

A feature request have been added earlier in the PHP repository: https://github.com/personnummer/php/issues/11

Ref wiki:
> Among the four last digits, the three first are a serial number. For the last digit among these three, an odd number is assigned to males and an even number to females.

**Comment by frozzare** [comment]
It could be a good thing to add, but I don't think it will be used so much.

**Comment by Johannestegner** [comment]
Right, it's also something that would really be simple enough for the end user to calculate them selves.
I propose that we leave the issue open and see if we get any more requests about it, if we do we can reconsidder :)

**Comment by frozzare** [comment]
Sounds good!

**Comment by frozzare** [comment]
@Johannestegner let's add `isMale` and `isFemale` to spec v2.1

**Comment by Johannestegner** [comment]
Sounds good to me!
