### ISSUE TITLE
[feature] GetAge

### ISSUE THREAD

**Issue by Johannestegner** [personnummer/meta#12]
A feature request was made in the php package ( https://github.com/personnummer/php/issues/11 ) in which a function to get age from a personnummer is requested.

I think the idea is valid, but it makes it hard when it comes to coordination numbers due to it adding +60 to the day (although it would be easy enough to see if it is one or not and in that case subtract 60 i guess!).

So request: Add a `GetAge(personnummer)` method.

**Comment by frozzare** [comment]
I think this should be used more than #11 and it's not so hard to implement and for coordination numbers we should subtract 60 to get the right day.

**Comment by Johannestegner** [comment]
In the request, the user proposes the use of Carbon (php), I do love carbon, but I do think that we should try stick to the built in versions as far as it goes (some TimeSpan structure I guess? :) ).

**Comment by frozzare** [comment]
Carbon is nice, but I don't we need Carbon just for getting the age of a personnummer. Let's try to stick with the built in util we need something like Carbon.
