### ISSUE TITLE
Personnummer object

### ISSUE THREAD

**Issue by Johannestegner** [personnummer/meta#13]
I have been thinking a bit about the codebase and current implementation as a static class that takes a number or string as argument in all cases...

I personally feel that it could be an idea to introduce a `parse` method to the static class, which returns a object (personnumer) which could store the information (if it is a valid number). That way one could invoke the methods that are added to the lib directly on a stored instance instead of always using the static class.

This would not change the current API and I do think that all methods in the current implementations should stay as they are and any new also introduced to the static class, this would just open up for a more object oriented type of approach to it.

What do you think about this idea @frozzare ? Too much for the lib maybe? Or do we want to add aditional complexity to the packages?

**Comment by frozzare** [comment]
I think it's a good idea but maybe too much complexity right now since the packages aren't that big. Maybe later if the packages that have static class gets too complex and big.

**Comment by Johannestegner** [comment]
Sounds good.

**Comment by Johannestegner** [comment]
Closing this one as it is now part of the discussion/draft of v3 spec.
