### ISSUE TITLE
Copyright row in license file

### ISSUE THREAD

**Issue by frozzare** [personnummer/meta#16]
Right now we have different ways to write the copyright row in the license files:

go:
```
Copyright (c) 2014-2019
```
dart:
```
Copyright (c) Personnummer
```
php:
```
Copyright (c) 2014-2017
```

What way should we use? @Johannestegner

**Comment by Johannestegner** [comment]
Good question... First off, I'm guessing all of them would support the utf char for (c), that is `U+00A9` / ©, maybe we would prefer that over (c)? Either way would be fine for me though.

When it comes to the year, 2014-2019 might be good yes also the org name (`Personnummer`) maybe `Personnummer and Contributors` + a contributors file in each repo?

So something like:

`Copyright © 2014-2019 - Personnummer and Contributors`  
alt  
`Copyright (c) 2014-2019 - Personnummer and Contributors`  

Honestly though, I'm not sure what the standard is and I can't find it online, so I'll give you the right to decide whatever you feel is the best looking and we go with that! ;D

**Comment by frozzare** [comment]
I prefer (c) over ©, so let's stick to that. Facebook use (c) https://github.com/facebook/react/blob/master/LICENSE 

This format looks good:
`Copyright (c) 2014-2019 - Personnummer and Contributors`

Let's update all license files to that format, no need to create new releases.
