### ISSUE TITLE
Create testdata in json or yaml format

### ISSUE THREAD

**Issue by frozzare** [personnummer/meta#21]
ping @Johannestegner

**Comment by Johannestegner** [comment]
https://gist.github.com/Johannestegner/7913d56ae441f6217a2cad513ec85922

As mentioned in #20, two files in the gist above, one with a bit more structure, one with all in a list. Do we want it in a gist or we want it directly in the meta repo?

**Comment by Johannestegner** [comment]
Also, Closing #20 :)

**Comment by frozzare** [comment]
@Johannestegner I think we should add in this repo, the link can be forgotten or removed or something :)

**Comment by Johannestegner** [comment]
#22, merging right away. :)
