### ISSUE TITLE
You should abandon the isValid method in V3

### ISSUE THREAD

**Issue by dannyhajj** [personnummer/meta#24]
I have some feedback regarding the V3 spec. I think you might need to reconsider a few decisions regarding errors and the `isValid` method.

According to the spec, an SSN should be validated with `Personnummer(ssn, options)->isValid()`. 

The issue with this approach is that the `Personnumer` object will be initialized in the constructor. So passing an invalid SSN **should not** allow the initialization to complete and should raise/throw during the initialization of the object.

The following code should fail and raise an error, so in theory, the `isValid` should always return `true`.

```
ssn = new Personnummer('not-a-valid-ssn')
```

So to verify an SSN, it should be like so (pseudo-code):

```js
function valid(string ssn) {
    try {
       parse(ssn)
       return true
    } catch (ParseException) {
        return false
    }
}

function parse(string ssn, array|object|languageSpecific options = []) {
    return new Personnummer(ssn, options)
}
```

**Comment by Johannestegner** [comment]
Hi @dannyhajj ! Thank you for the report!

We have discussed the issue and we agree with you, the `isValid` method/property is not needed. Instead the parse and (if applicable) constructor will throw an exception in case the SSN is not valid.

The spec will be updated shortly!

@frozzare Please close this issue once the spec is updated :)
