### ISSUE TITLE
Update packages to use github actions.

### ISSUE THREAD

**Issue by Johannestegner** [personnummer/meta#29]
At the moment, all packages uses either travis or other pipelines to test and deploy. I propose that we change to github actions for all projects.

**Comment by frozzare** [comment]
Sounds good! Maybe we should create some kind of package info file or add this info to the readme file?

**Comment by frozzare** [comment]
Packages left

https://github.com/personnummer/kotlin
https://github.com/personnummer/ruby
https://github.com/personnummer/swift

**Comment by frozzare** [comment]
Ruby is moved.

**Comment by frozzare** [comment]
Swift is moved.

**Comment by Johannestegner** [comment]
My big question is: Do we want to keep on maintaining the kotlin package?
Kotlin is a nice language and all, but it is basically a superset of Java, and all java packages can be used in Kotlin while I'm not sure if it works as good the other way around.

Is it worth having two packages to maintain for the same VM or should we deprecate the kotlin package for now?

**Comment by bombsimon** [comment]
I don't think that many people are using any of those packages but I definitely think it's worth keeping both since the chore of maintaining it is super low. If I started I new Kotlin project I would love to not have to pull in Java dependencies if possible. I think the same would go for Clojure which also runs on the JVM, or Elixir vs. Erlang on BEAM etc.

Maybe we can have it available and archive it next time some kind of maintenance is required since it doesn't cost us anything until that point?

**Comment by Johannestegner** [comment]
Aye @bombsimon , I have been thinking about it a bit too and I agree, the only issue is that it's still using the V1 api rather than V3. 
I'm not sure if I have time available in the near feature to patch it up. I have no issues at all to keep it around, but I think we should at the least try to patch it up to v3 for it to be worth keeping! :)

**Comment by bombsimon** [comment]
Oh, my bad! If it's already lagging behind just kill it!

Since [https://hacktoberfest.digitalocean.com/](Hacktoberfest) starts in just a few days, maybe worth worth creating some issues and wait until the end of October?

**Comment by Johannestegner** [comment]
Yes, that's not a bad idea!

**Comment by Johannestegner** [comment]
Closing for now, the packages not yet updated are either in deprecated state or requires a new maintainer. Will go through them soon and take it up in core after that! :)
