### ISSUE TITLE
Proposal: get real day method

### ISSUE THREAD

**Issue by frozzare** [personnummer/meta#30]
Today we can get the day from a social security number by a class property `$p->day` but that's not always the real day, e.g for coordination numbers. 

I propose that we add a new method that can return the real day for both social security numbers and coordination numbers. Not sure about what the best name for the method is.

```php
// the provided day
$p->day

// the real day
$p->getDay()
```

**Comment by Johannestegner** [comment]
I feel like the `day` property in that case should be the real day value as (for example) `65` is not a valid day. Maybe we should just allow for a `DateTime` type of structure to be fetched from the Personnummer to use as wanted?

```
DateTime pn = Personnummer::toDateTime();
pn.getDay(); // real day.
```

**Comment by bombsimon** [comment]
Some of the implementations has the class property as internal properties. The pseudo interface doesn't state if they should be private or not.

Most of the implementations use some kind of DateTime library to validate the dates and some stores that value in the class (such as `perl` and `cpp`, sorry 😃 ).

If the specification implies that the class properties are supposed to be public I agree that `day` should hold the real day. Maybe add a new property such as `parsedDay` or `originalDay` which returns whatever was fed to the constructor and don't add new methods?

**Comment by frozzare** [comment]
Oh, you're right about the public thing. I'm just assumed that it would be public. But isn't clear that it should be the real day or not, so that's my the idea about a new method.

Maybe we should move this to spec version 3.1 or something like that, where we add a new property `parsed/orginal` day instead of method and change the existing `day` property to be the real day. But it will be breaking changes for some packages (e.g js or dart), so we need to think of some good way of doing this.

**Comment by Johannestegner** [comment]
Closing this due to the v3.1 specification containing a date object (#51).
