### ISSUE TITLE
Proposal: Temporary Personal Numbers 

### ISSUE THREAD

**Issue by frozzare** [personnummer/meta#43]
**Description**

Moving discussion about T-numbers here since it's not just a JavaScript package feature request. Maybe a good fit for version 4 or something.

JavaScript implementation: https://github.com/personnummer/js/commit/56f9a5a2b61c41ed0c694ba46aec8cd3ae7bb59d

Old issue: https://github.com/personnummer/js/issues/211

**Breaking changes**

**Comment by Johannestegner** [comment]
Closing this, as it's in the specification as of #51
