### ISSUE TITLE
[FEATURE] - Get date of birth

### ISSUE THREAD

**Issue by crkt** [personnummer/meta#50]
**Description**

I have been using this api in other projects and found that as a consumer I end up doing things like this:

```typescript
const pnr = Personnummer.parse(personalIdentityNumber);

const { fullYear: year, month, day: dayString } = pnr;

let day = parseInt(dayString, 10);
if (pnr.isCoordinationNumber()) {
  day = day - 60;
}

const birthDate = new Date(`${year}-${month}-${day}`);
```

With the goal of getting a date and then working with the date to get diffs in different units, such as months, days or years. With `getAge` that already exists I lose some granularity such as months. 

It would be great to able to have a `Date` to work with to integrate nicely with other date libraries and getting difference in months or other units besides just year. And also avoiding having to know about coordination numbers in my consuming code. In my example I have to check if the personal identity number is a coordination number to figure out the date of birth.

**Breaking changes**

**Comment by Johannestegner** [comment]
Hi! Thank you for the feature request!

Sounds good to me, have basically done the same myself a few times, hehe.
@frozzare , I know you track this, so do you want to have the honor of checking with the rest of the team? :)

I'd say that there would be no breaking changes in this, so a major version of the API would not be required.

**Comment by frozzare** [comment]
I'll check with the rest of the team, and we should add this function in a new spec (3.1) and it's not a breaking thing so it will be easy to implement this in all packages.

**Comment by frozzare** [comment]
We've talked about this in our slack and we agree that we should expose the date and a lot of packages has the date object available already but maybe not public, but we agreed on adding `date` function/property (depending on language) that expose the date and not calling it `getDateOfBirth`, not all personnummer has a real date of birth so the naming can be confusing, so we think it's better to just call it `date`

**Comment by Johannestegner** [comment]
This feature have been added to the v3.1 specification in #51 and will be implemented in the packages asap :)
